### ISSUE TITLE
"data-carrousel-btn-previous-text" accepte le code HTML mais ce code est restitué dans le "title"

### ISSUE THREAD

**Issue by juliemoynat** [nico3333fr/jquery-accessible-carrousel-aria#13]
Salut,

J'ai découvert avec joie qu'on pouvait mettre du code HTML dans l'attribut "data-carrousel-btn-previous-text" parce que j'utilise une police d'icônes. Exemple : 
`<span class='icon-circle-arrow' aria-hidden='true'></span><span class='visually-hidden'>Show previous panel</span>`

Par contre, je vois que dans l'attribut "title" du bouton, les balises sont présentes aussi.
Est-ce qu'il est possible de supprimer les balises HTML lors de l'injection dans le "title" ?

Merci pour ton aide !

**Comment by nico3333fr** [comment]
Salut !

Ah, pour être franc, j'avais pas prévu ce cas !

Ceci dit, ce n'est pas bien grave, il faut que, sur le bout de code qui génère le title, je ne prenne que le texte. Y a une méthode jQuery qui fait ça, .text() je crois. J'y regarde durant le week-end, je te tiens au courant. ;)
