### ISSUE TITLE
Update demo code

### ISSUE THREAD

**Issue by Twikito** [nico3333fr/jquery-accessible-carrousel-aria#2]
For more optimization, like SEO, update demo code

``` html
<div class="carrousel__content">
    <h3>A first panel</h3>
    <p>Here the content.</p>
</div>
```

by 

``` html
<section class="carrousel__content">
    <header><h3>A first panel</h3><header>
    <p>Here the content.</p>
</section>
```

**Comment by nico3333fr** [comment]
I'll test if it is working, and if it is ok, I will add a mention of this :+1: 

(anyway, I've made the plugin as structure-agnostic as possible, so there will be probably other optimizations like this)

**Comment by goetsu** [comment]
bof bof et rebof chaque zone sera alors balisé comme "bannière" ce qui est loin d'être tip top

**Comment by Twikito** [comment]
Théoriquement et d'après le W3C, une section est une partie d'un contenu (d'un main ou article), et des balises header et hn doivent se retrouver dans une balise article ou section…
D'où ma suggestion :-)

**Comment by goetsu** [comment]
le carrousel lui même ne constituant pas dans la majorité des cas une unité éditoriale mais plutôt un agrégat de contenu disparate je ne vois pas l’intérêt de `<section>`. Si je devrais revoir la structure ça sera plutôt si le carrousel est dans un `<main>`, le mettre dans un `<section>` et avoir plusieurs `<article>` à l'intérieur pour chaque slide du carrousel.
De plus, il n'y a pas obligation d'avoir un header un hn suffit.
Mais bon à ce niveau là on rentre dans le pignolage de mouche

**Comment by Twikito** [comment]
Bon… même s'il manque les balises dans ta réponse (^^), je suis d'accord avec toi : tout dépend du contexte et du contenu ;-)

**Comment by goetsu** [comment]
corrigé

**Comment by nico3333fr** [comment]
Bon, je clos cette issue.
