### ISSUE TITLE
$activated is not defined

### ISSUE THREAD

**Issue by zomars** [nico3333fr/jquery-accessible-carrousel-aria#7]
I'm getting the following error: 

```
Uncaught ReferenceError: $activated is not defined
```

And it points me to this line: `jquery-accessible-carrousel-aria.js:464`

I'm using out of the box jQuery v2.2.4

**Comment by nico3333fr** [comment]
Hi @zomars ,

I've tested with the demo page with jQuery 2.2.4, I didn't get any problem. :-\

Do you have an example on a page that I could have a look ? This bug is strange.

Kind regards,
Nicolas

**Comment by zomars** [comment]
This only happens when trying to use the next and previous buttons, the pull request (#8) I made solves it.

**Comment by nico3333fr** [comment]
Great work, thanks a lot for pointing out this mistake I made! :+1:

**Comment by nico3333fr** [comment]
Thanks again, I've published your update to NPM/Bower and in the demo page: http://a11y.nicolas-hoffmann.net/carrousel/

**Comment by zomars** [comment]
Thanks a lot! I'm glad I could help. 💪
